#Here the token of your discord bot
Token: 'IMPORTANT'

#The channel where you want the messages
Channel-id: 'CHANNEL ID'

#Change default messages
Messages:
  server_on: 'the server started up'
  server_off: 'server stopped'
  join: 'joined the game'
  leave: 'left the game'

#Change color of the embeds
Colors: # needs to be in decimal
#Needs to be in decimal color code
  chat: 3459527
  server_on: 2472448
  server_off: 12204800
  join: 4388210
  leave: 16082498